name: Get Sentiment and update GitHub page

on:
  schedule:
    - cron: "5 7 * * *" # runs every half hour
    
jobs:
  refresh_page:
    runs-on: ubuntu-latest    
    steps:
      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script to update sentiment page
        run: python update_index.py
        
      - name: Clone repo from your github.io page and commit newly generated sentiment html file
        run: | #change all the "damianboh"s below to your username
          git clone https://github.com/chenpnn/plotly.git 
          cp index.html plotly/index.html
          cd plotly
          git add index.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh page'        
        
      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: #change all the "damianboh"s below to your username
          github_token: ${{ secrets.TOKEN }}          
          repository: "chenpnn/plotly"
          branch: "main"          
          directory: ./plotly
